
CREATE TABLE public.questions (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	answer varchar(255) NOT NULL,
	category varchar(255) NOT NULL,
	is_deleted bool NOT NULL,
	option1 varchar(255) NOT NULL,
	option2 varchar(255) NOT NULL,
	option3 varchar(255) NOT NULL,
	option4 varchar(255) NOT NULL,
	question varchar(255) NOT NULL,
	question_level varchar(255) NOT NULL,
	CONSTRAINT questions_pkey PRIMARY KEY (id)
);