--- JAVA QUESTIONS

INSERT INTO questions (answer, category, is_deleted, option1, option2, option3, option4, question, question_level) VALUES
('JVM', 'Java', false, 'JDK', 'JRE', 'JVM', 'JIT', 'Which component is responsible for executing Java bytecode?', 'EASY'),
('byte', 'Java', false, 'int', 'byte', 'short', 'long', 'Which of the following is the smallest data type in Java?', 'EASY'),
('Object Class', 'Java', false, 'String Class', 'Object Class', 'Class Class', 'Runtime Class', 'Which is the parent class of all Java classes?', 'EASY'),
('final', 'Java', false, 'static', 'final', 'abstract', 'private', 'Which keyword is used to prevent inheritance?', 'EASY'),
('== compares reference, equals() compares content', 'Java', false, 'Both compare values', '== compares content, equals() compares reference', '== compares reference, equals() compares content', 'They are same', 'Difference between == and equals() in Java?', 'MEDIUM'),
('Stack', 'Java', false, 'Heap', 'Stack', 'Method Area', 'Data Segment', 'Where are local variables stored in Java memory?', 'MEDIUM'),
('Garbage Collector', 'Java', false, 'Thread', 'Garbage Collector', 'Compiler', 'JRE Manager', 'Which component removes unused objects from memory?', 'EASY'),
('Interface', 'Java', false, 'Class', 'Abstract Class', 'Interface', 'Enum', 'Which is used to achieve 100% abstraction in Java?', 'MEDIUM'),
('Polymorphism', 'Java', false, 'Encapsulation', 'Abstraction', 'Polymorphism', 'Inheritance', 'Method overloading and overriding are examples of?', 'EASY'),
('String is immutable', 'Java', false, 'String is mutable', 'String is immutable', 'String is thread-safe', 'String is stored in heap only', 'Which statement is true about String in Java?', 'EASY'),
('Transient', 'Java', false, 'Synchronized', 'Transient', 'Native', 'Volatile', 'Which keyword prevents a variable from being serialized?', 'HARD'),
('finally always executes', 'Java', false, 'finally won’t execute if error occurs', 'finally executes only on success', 'finally always executes', 'finally executes only when return exists', 'Which is true about finally block in Java?', 'MEDIUM'),
('Checked Exception', 'Java', false, 'Unchecked Exception', 'Checked Exception', 'Runtime Error', 'Memory Leak', 'IOException is what type of exception?', 'EASY'),
('super()', 'Java', false, 'this()', 'super()', 'parent()', 'base()', 'Which keyword is used to call parent class constructor?', 'EASY'),
('Callable returns value, Runnable doesn’t', 'Java', false, 'Both return value', 'Runnable returns value, Callable doesn’t', 'Callable returns value, Runnable doesn’t', 'Both don’t return value', 'Difference between Runnable and Callable?', 'MEDIUM'),
('HashMap allows null key', 'Java', false, 'HashMap allows null key', 'HashMap doesn’t allow null key', 'Hashtable allows null key', 'Both allow null keys', 'Which is true about HashMap in Java?', 'MEDIUM'),
('synchronized keyword', 'Java', false, 'transient', 'volatile', 'synchronized', 'throw', 'Which keyword is used to make a method thread-safe?', 'MEDIUM'),
('ClassNotFoundException', 'Java', false, 'FileNotFoundException', 'NoSuchMethodException', 'ClassNotFoundException', 'IOException', 'Which exception is thrown when Class.forName() fails?', 'HARD'),
('JIT Compiler improves performance', 'Java', false, 'JIT slows performance', 'JIT is part of JVM', 'JIT Compiler improves performance', 'JIT compiles source code', 'Which statement is correct about JIT?', 'MEDIUM'),
('volatile ensures visibility of shared variables', 'Java', false, 'volatile ensures atomicity', 'volatile ensures thread creation', 'volatile ensures visibility of shared variables', 'volatile prevents serialization', 'What does volatile keyword guarantee in Java?', 'HARD');

INSERT INTO questions (answer, category, is_deleted, option1, option2, option3, option4, question, question_level) VALUES
('public', 'Java', false, 'private', 'public', 'protected', 'default', 'Which access modifier allows access from anywhere?', 'EASY'),
('JRE', 'Java', false, 'JVM', 'JRE', 'JDK', 'JIT', 'Which contains JVM + libraries required to run Java programs?', 'EASY'),
('Heap Memory', 'Java', false, 'Stack Memory', 'Heap Memory', 'Method Area', 'Register', 'Where are objects stored in Java memory?', 'EASY'),
('Abstract Class', 'Java', false, 'Final Class', 'Abstract Class', 'Concrete Class', 'Enum', 'Which class cannot be instantiated but can have constructors?', 'MEDIUM'),
('Serialization', 'Java', false, 'Multithreading', 'Serialization', 'Encapsulation', 'Polymorphism', 'Converting object into byte stream is called?', 'EASY'),
('synchronized block is faster than synchronized method', 'Java', false, 'Both are same', 'synchronized method is faster', 'synchronized block is faster than synchronized method', 'none', 'Which is true about synchronized block vs method?', 'MEDIUM'),
('Thread', 'Java', false, 'Runnable', 'Thread', 'Executor', 'Callable', 'Which class provides direct multi-threading support?', 'EASY'),
('static block', 'Java', false, 'constructor', 'static block', 'main method', 'object block', 'Which block runs before main() method?', 'MEDIUM'),
('Throw keyword', 'Java', false, 'Throws keyword', 'Throw keyword', 'Catch block', 'Finally block', 'Which is used to manually throw an exception?', 'EASY'),
('Runtime Exception', 'Java', false, 'Checked Exception', 'Runtime Exception', 'Error', 'User Defined Exception', 'NullPointerException is what type of exception?', 'EASY'),
('native keyword', 'Java', false, 'native', 'volatile', 'default', 'strictfp', 'Which keyword is used to call non-Java code?', 'HARD'),
('Daemon Thread', 'Java', false, 'Main Thread', 'Daemon Thread', 'Worker Thread', 'User Thread', 'Which thread runs in background and stops when main thread ends?', 'MEDIUM'),
('Class Loader', 'Java', false, 'Compiler', 'JVM', 'Class Loader', 'JIT', 'Which component loads bytecode into memory?', 'MEDIUM'),
('StringBuilder is not thread-safe', 'Java', false, 'StringBuilder is thread-safe', 'StringBuffer is not thread-safe', 'StringBuilder is not thread-safe', 'Both are thread-safe', 'Which one is true?', 'MEDIUM'),
('JDK includes JRE + development tools', 'Java', false, 'JDK includes only JVM', 'JDK includes JRE + development tools', 'JDK only installs JRE', 'JDK is older than JVM', 'Which statement is correct about JDK?', 'EASY'),
('super keyword gives access to parent methods', 'Java', false, 'super creates instance', 'super calls static methods', 'super keyword gives access to parent methods', 'super is used to access child method', 'Which statement is true about super keyword?', 'EASY'),
('Function Interface has exactly one abstract method', 'Java', false, 'It has multiple methods', 'It contains no method', 'Function Interface has exactly one abstract method', 'It cannot be used with lambda', 'Which is true about Functional Interface?', 'MEDIUM'),
('Default method', 'Java', false, 'Static method', 'Private method', 'Default method', 'Native method', 'Which type of method can be defined inside an interface from Java 8?', 'HARD'),
('ConcurrentHashMap is thread-safe', 'Java', false, 'HashMap is thread-safe', 'ConcurrentHashMap is thread-safe', 'Hashtable is not thread-safe', 'TreeMap is thread-safe', 'Which map is thread-safe without synchronization?', 'MEDIUM'),
('BufferedReader is faster than Scanner', 'Java', false, 'Scanner is faster', 'BufferedReader is faster', 'Both same speed', 'Depends on JVM', 'Which is faster for reading large input?', 'HARD');

--- MICROSERVICE QUESTIONS

INSERT INTO questions (answer, category, is_deleted, option1, option2, option3, option4, question, question_level) VALUES
('Service Registry', 'Microservices', false, 'API Gateway', 'Service Registry', 'Message Broker', 'Config Server', 'Which component stores and exposes the locations of running service instances?', 'EASY'),
('Client-side discovery', 'Microservices', false, 'Client-side discovery', 'Server-side discovery', 'Static routing', 'DNS round robin', 'When a caller queries the registry and chooses a target instance itself, what pattern is this?', 'EASY'),
('Spring Cloud Gateway', 'Microservices', false, 'Spring Cloud Gateway', 'Spring Batch', 'Spring Data JPA', 'Spring AOP', 'Which Spring project is commonly used as an API Gateway?', 'EASY'),
('Configuration externalized from the service', 'Microservices', false, 'Configuration bundled in JAR', 'Configuration externalized from the service', 'Binary-embedded YAML', 'Per-pod hardcoded values', 'What is a key principle of centralized configuration in microservices?', 'EASY'),
('Circuit Breaker', 'Microservices', false, 'Retry', 'Bulkhead', 'Circuit Breaker', 'Rate Limiter', 'Which resilience pattern stops calls to an unhealthy dependency to fail fast?', 'EASY'),
('Bulkhead isolates resources per dependency', 'Microservices', false, 'Retry is same as Bulkhead', 'Bulkhead isolates resources per dependency', 'Bulkhead increases request rate', 'Bulkhead disables timeouts', 'Which statement about the Bulkhead pattern is correct?', 'MEDIUM'),
('Idempotency', 'Microservices', false, 'Idempotency', 'Strong consistency', 'Global transactions', 'Sticky sessions', 'Which concept ensures a repeated request produces the same effect as a single request?', 'MEDIUM'),
('SAGA pattern', 'Microservices', false, 'Two-phase commit', 'SAGA pattern', 'Single DB per service', 'CQRS only', 'Which approach coordinates distributed transactions using local transactions and compensations?', 'MEDIUM'),
('Asynchronous communication reduces coupling', 'Microservices', false, 'Async requires shared DB', 'Asynchronous communication reduces coupling', 'Async always faster than sync', 'Async disables retries', 'Which is generally true about asynchronous messaging between services?', 'MEDIUM'),
('API composition', 'Microservices', false, 'Event sourcing', 'API composition', 'Replication', 'Sharding', 'What pattern aggregates data from multiple services for a single client request?', 'MEDIUM'),
('Config Server with Git backend', 'Microservices', false, 'Hardcode values in code', 'Env-only variables', 'Config Server with Git backend', 'Store config in client cookies', 'In Spring Cloud, what is a common way to centralize configuration across services?', 'EASY'),
('Service per database', 'Microservices', false, 'Shared monolithic DB', 'Global ACID transactions', 'Service per database', 'One DB per team', 'Which data ownership strategy best aligns with microservice boundaries?', 'MEDIUM'),
('Server-side discovery', 'Microservices', false, 'Client-side discovery', 'Sticky discovery', 'Server-side discovery', 'Eager discovery', 'In Kubernetes, when a Service/Ingress routes to Pods after looking up endpoints, which discovery style is used?', 'MEDIUM'),
('Distributed tracing with correlation IDs', 'Microservices', false, 'Only local logs', 'Single server logs', 'Distributed tracing with correlation IDs', 'Turn off logs in prod', 'What is essential to trace requests across multiple microservices?', 'MEDIUM'),
('Rate Limiter', 'Microservices', false, 'Retry', 'Rate Limiter', 'Time Limiter', 'Cache Aside', 'Which pattern controls how many requests a client can make in a time window?', 'EASY'),
('Blue-Green deployment reduces downtime by switching traffic between two identical environments', 'Microservices', false, 'Blue-Green doubles DB writes', 'Blue-Green removes rollbacks', 'Blue-Green deployment reduces downtime by switching traffic between two identical environments', 'Blue-Green is only for monoliths', 'Which is true about Blue-Green deployments?', 'MEDIUM'),
('Canary release', 'Microservices', false, 'Canary release', 'Shadow traffic', 'Dark launch', 'Chaos testing', 'What technique sends a small percentage of production traffic to a new version first?', 'MEDIUM'),
('Sidecar proxy (service mesh)', 'Microservices', false, 'Direct SDK in each service', 'Sidecar proxy (service mesh)', 'Shared library in all teams', 'Hardcoded endpoints', 'What approach offloads cross-cutting concerns like mTLS, retries, and telemetry from services?', 'HARD'),
('Event sourcing stores the state as a sequence of events', 'Microservices', false, 'Event sourcing stores only current state', 'Event sourcing stores the state as a sequence of events', 'Event sourcing requires 2PC', 'Event sourcing forbids CQRS', 'Which statement about event sourcing is correct?', 'HARD'),
('Dead letter queue (DLQ)', 'Microservices', false, 'Primary exchange', 'Fanout exchange', 'Dead letter queue (DLQ)', 'Round-robin queue', 'What messaging feature safely isolates messages that repeatedly fail processing?', 'MEDIUM');

INSERT INTO questions (answer, category, is_deleted, option1, option2, option3, option4, question, question_level) VALUES
('Choreography', 'Microservices', false, 'Orchestration', 'Choreography', 'Central middleware', 'Global scheduler', 'What is it called when services react to each other''s events without a central coordinator?', 'MEDIUM'),
('ELK or EFK stack', 'Microservices', false, 'ELK or EFK stack', 'Only stdout logging', 'Direct DB ingestion', 'Client-side logging', 'Which is a common centralized logging approach for microservices?', 'EASY'),
('Saga pattern coordinates transactions with compensating actions', 'Microservices', false, 'Saga is a global ACID transaction', 'Saga rolls back the entire system', 'Saga pattern coordinates transactions with compensating actions', 'Saga requires a shared DB', 'Which statement is true about the Saga pattern?', 'MEDIUM'),
('API Gateway handles cross-cutting concerns such as authentication and routing', 'Microservices', false, 'API Gateway executes business logic', 'API Gateway replaces the config server', 'API Gateway handles cross-cutting concerns such as authentication and routing', 'API Gateway stores cache only', 'Which is a typical responsibility of an API gateway?', 'MEDIUM'),
('OpenTracing or OpenTelemetry', 'Microservices', false, 'Distributed JDBC', 'OpenTracing or OpenTelemetry', 'System.out.println', 'Spring AOP only', 'Which library or standard is used for distributed tracing?', 'MEDIUM'),
('REST is stateless, while gRPC supports streaming and binary data', 'Microservices', false, 'REST supports streaming, gRPC is HTTP-only', 'REST is binary, gRPC is text-based', 'REST is stateless, while gRPC supports streaming and binary data', 'REST requires protobuf', 'Which statement explains a difference between REST and gRPC?', 'MEDIUM'),
('Sidecar pattern', 'Microservices', false, 'Chain of Responsibility', 'Singleton pattern', 'Sidecar pattern', 'Decorator pattern', 'Which pattern runs helper processes alongside the service in the same host/pod?', 'EASY'),
('Service Mesh', 'Microservices', false, 'Circuit Mesh', 'Log Aggregation', 'Service Mesh', 'Service Split', 'What provides infrastructure-level features like traffic routing, observability, and policy enforcement between services?', 'MEDIUM'),
('Domain-Driven Design (DDD)', 'Microservices', false, 'Monolith-first', 'Domain-Driven Design (DDD)', 'Database Normalization', 'Test-Driven Services', 'Which methodology helps identify service boundaries based on business domains?', 'MEDIUM'),
('CQRS separates read and write models', 'Microservices', false, 'CQRS merges all data into one model', 'CQRS separates read and write models', 'CQRS depends on two-phase commit', 'CQRS eliminates eventual consistency', 'Which statement accurately describes CQRS in microservices?', 'HARD'),
('Idempotent endpoints allow safe retries', 'Microservices', false, 'Idempotent endpoints allow safe retries', 'Idempotent only applies to GET requests', 'Idempotent disables logging', 'Idempotent removes rate limiting', 'What is the benefit of idempotent operations in distributed systems?', 'MEDIUM'),
('Eureka, Consul, and Zookeeper', 'Microservices', false, 'Eureka, Consul, and Zookeeper', 'Only Spring Cloud', 'MySQL and PostgreSQL', 'Kafka and RabbitMQ', 'Which tools are commonly used for service discovery?', 'EASY'),
('Rollback and retry behaviors are not centralized', 'Microservices', false, 'Distributed transactions are always atomic', 'Rollback and retry behaviors are not centralized', 'Distributed transactions guarantee zero failures', 'Distributed transactions simplify orchestration', 'Which challenge exists in distributed transactions?', 'HARD'),
('Deployment rollback', 'Microservices', false, 'Feature toggles', 'Chaos engineering', 'Deployment rollback', 'Central logging', 'What is commonly used to undo a faulty microservices deployment?', 'EASY'),
('Immutable infrastructure treats servers as disposable', 'Microservices', false, 'Immutable infrastructure allows live patching', 'Immutable infrastructure treats servers as disposable', 'Immutable infrastructure updates configuration only', 'Immutable infrastructure removes version control', 'Which statement is true about immutable infrastructure?', 'HARD'),
('Twelve-Factor App methodology', 'Microservices', false, 'SOLID Patterns', 'Twelve-Factor App methodology', 'Lean Startup', 'Waterfall Method', 'Which methodology provides best practices for building scalable microservices?', 'MEDIUM'),
('API versioning prevents breaking changes', 'Microservices', false, 'API versioning prevents breaking changes', 'API versioning increases coupling', 'API versioning reduces service uptime', 'API versioning disables backward compatibility', 'Why is API versioning important in microservices?', 'MEDIUM'),
('Dead Letter Queue handles messages failing after retries', 'Microservices', false, 'Dead Letter Queue stores success responses', 'Dead Letter Queue handles messages failing after retries', 'Dead Letter Queue broadcasts all messages', 'Dead Letter Queue triggers JVM restarts', 'What is the role of a Dead Letter Queue in messaging systems?', 'EASY'),
('GitOps relies on Git as a single source of truth for deployments', 'Microservices', false, 'GitOps disables CI/CD', 'GitOps deploys with FTP', 'GitOps relies on Git as a single source of truth for deployments', 'GitOps only works with Docker Compose', 'Which statement describes GitOps in microservices?', 'HARD'),
('Chaos Engineering validates system resilience by intentionally causing failures', 'Microservices', false, 'Chaos Engineering prevents changes in production', 'Chaos Engineering monitors successful requests only', 'Chaos Engineering validates system resilience by intentionally causing failures', 'Chaos Engineering disables error handling', 'What does Chaos Engineering aim to achieve?', 'HARD');

--POSTGRE SQL

INSERT INTO questions (answer, category, is_deleted, option1, option2, option3, option4, question, question_level) VALUES
('\l', 'PostgreSQL', false, '\dn', '\dt', '\l', '\du', 'Which command lists databases in psql?', 'EASY'),
('JSONB', 'PostgreSQL', false, 'XML', 'TEXT', 'BYTEA', 'JSONB', 'Which data type stores JSON efficiently in PostgreSQL?', 'EASY'),
('SERIAL', 'PostgreSQL', false, 'SERIAL', 'SMALLSERIAL', 'IDENTITY', 'BIGSERIAL', 'Which serial type auto-increments 32-bit?', 'EASY'),
('\dt', 'PostgreSQL', false, '\df', '\dt', '\dn', '\d', 'Which command lists tables in current schema?', 'EASY'),
('uuid-ossp', 'PostgreSQL', false, 'uuid-ossp', 'pgcrypto', 'postgis', 'hstore', 'Which extension provides UUID generation?', 'EASY'),
('NOW()', 'PostgreSQL', false, 'DATE()', 'NOW()', 'SYSDATE', 'CURRENT_TIME', 'Which function returns current timestamp?', 'EASY'),
('5432', 'PostgreSQL', false, '6379', '1521', '3306', '5432', 'What is the default port of PostgreSQL?', 'EASY'),
('@>', 'PostgreSQL', false, '||', '@>', '->', '#>', 'Which operator checks containment for JSONB?', 'EASY'),
('\d table', 'PostgreSQL', false, '\h table', '\dt+', '\c table', '\d table', 'Which command describes a table in psql?', 'EASY'),
('pg_dump', 'PostgreSQL', false, 'pg_basebackup', 'VACUUM', 'pg_dump', 'rsync', 'Which tool is a logical backup?', 'EASY'),
('ON CONFLICT ... DO UPDATE', 'PostgreSQL', false, 'INSERT OR UPDATE', 'REPLACE INTO', 'INSERT IGNORE', 'ON CONFLICT ... DO UPDATE', 'Which keyword upserts in PostgreSQL?', 'EASY'),
('plpgsql', 'PostgreSQL', false, 'plpgsql', 'pllua', 'plv8', 'pljava', 'Which is a procedural language supported out of the box?', 'EASY'),
('EXPLAIN', 'PostgreSQL', false, 'PLAN', 'EXPLAIN', 'PROFILE', 'TRACE', 'Which command shows query plan?', 'EASY'),
('B-Tree', 'PostgreSQL', false, 'GiST', 'BRIN', 'B-Tree', 'GIN', 'Which index type is default?', 'EASY'),
('Reclaims storage and updates visibility map', 'PostgreSQL', false, 'Runs ANALYZE only', 'Encrypts data', 'Creates backup', 'Reclaims storage and updates visibility map', 'What does VACUUM do?', 'EASY'),
('\timing', 'PostgreSQL', false, '\time', 'SET TIMING ON', '\timing', 'SHOW TIMING', 'Which command enables timing in psql?', 'EASY'),
('xmin/xmax visibility', 'PostgreSQL', false, 'fsync', 'WAL', 'TOAST', 'xmin/xmax visibility', 'Which feature implements MVCC snapshots?', 'EASY'),
('GIN on tsvector', 'PostgreSQL', false, 'B-Tree on text', 'BRIN on text', 'GIN on tsvector', 'Hash on text', 'Which index type is best for full-text search?', 'EASY'),
('CREATE DATABASE', 'PostgreSQL', false, 'NEW DB', 'INIT DB', 'CREATE DATABASE', 'CREATE SCHEMA', 'Which command creates a database?', 'EASY'),
('postgresql.conf', 'PostgreSQL', false, 'pg_log.conf', 'pg_ident.conf', 'postgresql.conf', 'pg_hba.conf', 'Which file stores server logs configuration by default?', 'EASY'),
('Client authentication and access rules', 'PostgreSQL', false, 'Replication slots', 'Client authentication and access rules', 'Shared buffers', 'Autovacuum frequency', 'What does pg_hba.conf control?', 'MEDIUM'),
('Containment/array/JSONB ops', 'PostgreSQL', false, 'Equality on scalar', 'Time-series', 'Geospatial search', 'Containment/array/JSONB ops', 'What is a GIN index best for?', 'MEDIUM'),
('Automatic vacuuming/analyze of tables', 'PostgreSQL', false, 'Backups', 'Automatic vacuuming/analyze of tables', 'Sharding', 'Failover', 'What is autovacuum responsible for?', 'MEDIUM'),
('Heap Only Tuple update avoiding index churn', 'PostgreSQL', false, 'High-availability transaction', 'High-optimized trigger', 'Heap Only Tuple update avoiding index churn', 'Heavy object transfer', 'What is a HOT update?', 'MEDIUM'),
('archive_mode = on', 'PostgreSQL', false, 'fsync = off', 'wal_level = minimal', 'archive_mode = on', 'track_io_timing = on', 'Which setting enables WAL archiving?', 'MEDIUM'),
('Slot retaining WAL for replica/consumer', 'PostgreSQL', false, 'Index slot', 'User role', 'Slot retaining WAL for replica/consumer', 'Backup slot', 'What is a replication slot?', 'MEDIUM'),
('pg_ctl promote', 'PostgreSQL', false, 'pg_basebackup --promote', 'pg_ctl promote', 'pg_promote()', 'SELECT promote();', 'Which command promotes a standby to primary?', 'MEDIUM'),
('Updates table statistics for planner', 'PostgreSQL', false, 'Reindexes indexes', 'Backs up database', 'Updates table statistics for planner', 'Cleans dead tuples', 'What does ANALYZE do?', 'MEDIUM'),
('->', 'PostgreSQL', false, '->', '#>', '->>', '#>>', 'Which function extracts JSONB field as JSONB?', 'MEDIUM'),
('READ COMMITTED', 'PostgreSQL', false, 'SERIALIZABLE', 'REPEATABLE READ', 'READ COMMITTED', 'READ UNCOMMITTED', 'Which isolation level is PostgreSQL default?', 'MEDIUM'),
('REFRESH MATERIALIZED VIEW', 'PostgreSQL', false, 'REFRESH MATERIALIZED VIEW', 'VACUUM MATERIALIZED VIEW', 'REBUILD VIEW', 'ANALYZE VIEW', 'What is a materialized view refresh method?', 'MEDIUM'),
('Large values out-of-line', 'PostgreSQL', false, 'System catalogs', 'Temp tables', 'Indexes only', 'Large values out-of-line', 'What does TOAST store?', 'MEDIUM'),
('postgis', 'PostgreSQL', false, 'postgis', 'citext', 'dblink', 'pgcrypto', 'Which extension adds geospatial types?', 'MEDIUM'),
('Lower latency at risk of losing recent commits on crash', 'PostgreSQL', false, 'Faster checkpoints', 'No WAL written', 'Safe synchronous replication', 'Lower latency at risk of losing recent commits on crash', 'What is synchronous_commit = off effect?', 'MEDIUM'),
('GiST', 'PostgreSQL', false, 'GiST', 'GIN', 'Hash', 'BRIN', 'Which index supports nearest-neighbor for polygons?', 'MEDIUM'),
('Very large, naturally ordered data', 'PostgreSQL', false, 'High-cardinality random text', 'Very large, naturally ordered data', 'Exact equality int', 'JSONB ops', 'What is a BRIN index good for?', 'MEDIUM'),
('Current sessions and queries', 'PostgreSQL', false, 'Only locks', 'Current sessions and queries', 'Only storage', 'Only buffers', 'What does pg_stat_activity show?', 'MEDIUM'),
('to_tsvector()', 'PostgreSQL', false, 'tsquery()', 'ts_rank()', 'to_tsvector()', 'ts_headline()', 'Which function builds tsvector from text?', 'MEDIUM'),
('Flush dirty pages, limit recovery time', 'PostgreSQL', false, 'Rotate logs', 'Vacuum catalog', 'Gather stats', 'Flush dirty pages, limit recovery time', 'What is the purpose of checkpoint?', 'MEDIUM'),
('PUBLICATION/SUBSCRIPTION', 'PostgreSQL', false, 'pg_dump', 'PUBLICATION/SUBSCRIPTION', 'Shared buffers', 'FDW only', 'Which feature supports logical replication?', 'MEDIUM'),
('WAL logging for data changes', 'PostgreSQL', false, 'WAL logging for data changes', 'Indexing', 'Visibility rules', 'Foreign keys', 'What does UNLOGGED table skip?', 'MEDIUM'),
('JSONB with GIN', 'PostgreSQL', false, 'ARRAY only', 'EAV tables', 'XML only', 'JSONB with GIN', 'How to store key/value without schema rigidity?', 'MEDIUM'),
('Per operation memory for sorts/hashes', 'PostgreSQL', false, 'Per operation memory for sorts/hashes', 'Shared buffer size', 'Autovacuum workers', 'WAL size', 'What does work_mem affect?', 'MEDIUM'),
('REINDEX', 'PostgreSQL', false, 'REINDEX', 'RESET INDEX', 'CLUSTER', 'VACUUM FREEZE', 'Which command reclaims bloat in indexes?', 'MEDIUM'),
('Extension for logical replication', 'PostgreSQL', false, 'Autovacuum daemon', 'Connection pooler', 'Extension for logical replication', 'Backup tool', 'What is pglogical?', 'MEDIUM'),
('All of these can', 'PostgreSQL', false, 'pgPool-II', 'pgBouncer', 'HAProxy', 'All of these can', 'Which tool pools connections for PostgreSQL?', 'MEDIUM'),
('More data cached in memory', 'PostgreSQL', false, 'Less connections', 'More data cached in memory', 'Less WAL generated', 'Faster autovacuum', 'What is the effect of setting shared_buffers higher?', 'MEDIUM'),
('Execution timing and buffer usage', 'PostgreSQL', false, 'Only row counts', 'Execution timing and buffer usage', 'Only plan', 'Only I/O stats', 'What does EXPLAIN (ANALYZE, BUFFERS) add?', 'MEDIUM'),
('pg_locks view', 'PostgreSQL', false, 'pg_locks view', 'SHOW LOCKS', '\locks', 'LOCKS()', 'Which command shows locks?', 'MEDIUM'),
('Physical replication and some logical', 'PostgreSQL', false, 'Physical replication and some logical', 'Disabling WAL', 'Only local development', 'Full text search', 'What is wal_level = replica required for?', 'MEDIUM'),
('Memory for temporary tables', 'PostgreSQL', false, 'Memory for temporary tables', 'Checkpoint size', 'Replication', 'Shared pool', 'What does temp_buffers configure?', 'MEDIUM'),
('GRANT CONNECT ON DATABASE db TO role;', 'PostgreSQL', false, 'CREATE ROLE role;', 'GRANT CONNECT ON DATABASE db TO role;', 'GRANT USAGE ON SCHEMA;', 'GRANT LOGIN TO role;', 'How to grant connect to a DB?', 'MEDIUM'),
('CREATEDB', 'PostgreSQL', false, 'CREATEDB', 'SUPERUSER', 'BYPASSRLS', 'REPLICATION', 'Which role attribute allows creating DBs?', 'MEDIUM'),
('Policies restricting row access per role', 'PostgreSQL', false, 'Index encryption', 'Only column masking', 'FDW setup', 'Policies restricting row access per role', 'What is RLS (Row Level Security)?', 'MEDIUM'),
('pg_stat_progress_vacuum', 'PostgreSQL', false, 'pg_stat_statements', 'pg_stat_bgwriter', 'pg_stat_user_tables', 'pg_stat_progress_vacuum', 'Which view tracks autovacuum activity?', 'MEDIUM'),
('pg_stat_statements', 'PostgreSQL', false, 'pg_repack', 'pg_trgm', 'intarray', 'pg_stat_statements', 'Which extension tracks normalized query stats?', 'MEDIUM'),
('GENERATED ALWAYS AS (...) STORED', 'PostgreSQL', false, 'COMPUTED BY (...)', 'GENERATED ALWAYS AS (...) STORED', 'VIRTUAL COLUMN', 'CREATE GENERATED COLUMN', 'How to create generated columns?', 'MEDIUM'),
('Client authentication and access rules', 'PostgreSQL', false, 'Replication slots', 'Client authentication and access rules', 'Autovacuum frequency', 'Shared buffers', 'What does pg_hba.conf control? (v2)', 'MEDIUM'),
('Containment/array/JSONB ops', 'PostgreSQL', false, 'Equality on scalar', 'Geospatial search', 'Containment/array/JSONB ops', 'Time-series', 'What is a GIN index best for? (v2)', 'MEDIUM'),
('Automatic vacuuming/analyze of tables', 'PostgreSQL', false, 'Failover', 'Sharding', 'Automatic vacuuming/analyze of tables', 'Backups', 'What is autovacuum responsible for? (v2)', 'MEDIUM'),
('Mark tuples with FrozenXID to avoid wraparound', 'PostgreSQL', false, 'Drop dead rows only', 'Sync replica', 'Force full rewrite always', 'Mark tuples with FrozenXID to avoid wraparound', 'What is VACUUM FREEZE used for?', 'HARD'),
('XID space exhaustion (~2^31 transactions)', 'PostgreSQL', false, 'XID space exhaustion (~2^31 transactions)', 'Large shared buffers', 'High CPU load', 'Too many indexes', 'What causes transaction ID wraparound risk?', 'HARD'),
('Prunes dead HOT chains to shorten index lookups', 'PostgreSQL', false, 'Disables vacuum', 'Forces CLUSTER', 'Drops indexes', 'Prunes dead HOT chains to shorten index lookups', 'How does HOT pruning help performance?', 'HARD'),
('GIN with pg_trgm', 'PostgreSQL', false, 'BRIN', 'Hash', 'GiST with cube', 'GIN with pg_trgm', 'Which index supports trigram similarity search?', 'HARD'),
('Track pages without dead tuples for index-only scans', 'PostgreSQL', false, 'Track pages without dead tuples for index-only scans', 'Track WAL segments', 'Track FSM pages', 'Track autovacuum', 'What is a visibility map used for?', 'HARD'),
('Extracting changes from WAL for subscribers', 'PostgreSQL', false, 'Extracting changes from WAL for subscribers', 'Decoding JSONB', 'Analyzing EXPLAIN', 'Transforming encodings', 'What is logical decoding?', 'HARD'),
('Define standbys required to confirm commit', 'PostgreSQL', false, 'Name of checkpoint', 'Name of archive dir', 'Define standbys required to confirm commit', 'Name of extension', 'Why use synchronous_standby_names?', 'HARD'),
('Latency increase during checkpoint flushes', 'PostgreSQL', false, 'Planner replan', 'Latency increase during checkpoint flushes', 'Sudden autovacuum start', 'Failover event', 'What is a checkpoint spike?', 'HARD'),
('Leader process spawns workers for parts of plan nodes', 'PostgreSQL', false, 'Leader process spawns workers for parts of plan nodes', 'Threads inside backend', 'FDW only', 'External engine', 'How does parallel query work in PostgreSQL?', 'HARD'),
('Just-in-time compilation of expressions/loops', 'PostgreSQL', false, 'Just-in-time compilation of expressions/loops', 'Join-in-time', 'JSON indexing technique', 'Job interval tuning', 'What does JIT do in PostgreSQL?', 'HARD'),
('High write speed with data loss risk on crash', 'PostgreSQL', false, 'Row-level security', 'Safer replication', 'Guaranteed durability', 'High write speed with data loss risk on crash', 'Why would you use UNLOGGED tables?', 'HARD'),
('Prevent torn pages by logging full page images after first change post-checkpoint', 'PostgreSQL', false, 'Prevent torn pages by logging full page images after first change post-checkpoint', 'Disable WAL', 'Tune autovacuum', 'Speed up selects', 'What is full_page_writes for?', 'HARD'),
('Time to wait before checking for deadlocks', 'PostgreSQL', false, 'Max lock time', 'Time to wait before checking for deadlocks', 'Statement timeout', 'Idle timeout', 'What is deadlock_timeout?', 'HARD'),
('Autovacuum threshold for anti-wraparound vacuums', 'PostgreSQL', false, 'Max WAL age', 'Max row age for HOT', 'Autovacuum threshold for anti-wraparound vacuums', 'Max age of backups', 'What is the purpose of freeze_max_age?', 'HARD'),
('Bitmap Heap Scan / Bitmap Index Scan', 'PostgreSQL', false, 'Seq Scan only', 'Bitmap Heap Scan / Bitmap Index Scan', 'Index Only Scan only', 'CTE Scan', 'Which EXPLAIN node indicates bitmap usage?', 'HARD'),
('Join corresponding partitions independently for performance', 'PostgreSQL', false, 'To skip constraints', 'For unique indexes only', 'Join corresponding partitions independently for performance', 'To avoid statistics', 'Why use partition-wise joins?', 'HARD'),
('Planner discouraged from using sequential scans', 'PostgreSQL', false, 'Planner discouraged from using sequential scans', 'Speed up autovacuum', 'Disable seq scans entirely', 'Force nested loops', 'What is the effect of enable_seqscan=off?', 'HARD'),
('Planner estimate of OS+shared cache for costing', 'PostgreSQL', false, 'Shared buffers size', 'work_mem size', 'Planner estimate of OS+shared cache for costing', 'WAL size', 'What does effective_cache_size influence?', 'HARD'),
('Index-only scans efficiency and pruning cost', 'PostgreSQL', false, 'Checkpoint frequency', 'Index-only scans efficiency and pruning cost', 'Replication lag', 'Autovacuum workers', 'What does HOT chain length impact?', 'HARD'),
('Lower risk of data loss vs higher write latency', 'PostgreSQL', false, 'No need for WAL', 'Lower risk of data loss vs higher write latency', 'Higher throughput always', 'No impact', 'What is synchronous replication tradeoff?', 'HARD'),
('Rebuild tables/indexes online to reduce bloat', 'PostgreSQL', false, 'Rebuild tables/indexes online to reduce bloat', 'Encrypt data', 'Backup database', 'Analyze statistics', 'Why use pg_repack?', 'HARD'),
('Compress full-page images/WAL records to reduce size', 'PostgreSQL', false, 'Compress tables', 'Compress full-page images/WAL records to reduce size', 'Compress indexes', 'Compress logs only', 'What is the role of wal_compression?', 'HARD'),
('SSI detects dangerous structures and aborts to ensure serializability', 'PostgreSQL', false, 'No anomalies at all', 'Classic strict 2PL', 'SSI detects dangerous structures and aborts to ensure serializability', 'Weaker than REPEATABLE READ', 'What is SERIALIZABLE snapshot isolation doing in PG?', 'HARD'),
('Location of write-ahead logs', 'PostgreSQL', false, 'Temp files', 'Location of write-ahead logs', 'Config backups', 'Base tables', 'What is pg_wal directory?', 'HARD'),
('Fraction of table updates triggering vacuum', 'PostgreSQL', false, 'Fraction of table updates triggering vacuum', 'Freeze age', 'Max autovacuum workers', 'Min freeze age', 'What is autovacuum_vacuum_scale_factor?', 'HARD'),
('Tiny size and good for ranged ordered data', 'PostgreSQL', false, 'Supports unique constraints', 'Tiny size and good for ranged ordered data', 'Better for equality lookups', 'Faster for all queries', 'Why might BRIN be preferred over B-Tree?', 'HARD'),
('Prevents vacuum from removing tuples needed by replicas', 'PostgreSQL', false, 'Stats collector feedback', 'Client notice', 'Feedback to planner', 'Prevents vacuum from removing tuples needed by replicas', 'What is a standby feedback?', 'HARD'),
('Data required by your snapshot has been removed', 'PostgreSQL', false, 'Vacuum canceled', 'Outdated statistics', 'Old EXPLAIN plan', 'Data required by your snapshot has been removed', 'What is a snapshot too old error (when enabled)?', 'HARD'),
('Stream WAL to a file/archive outside server', 'PostgreSQL', false, 'Replay WAL', 'Stream WAL to a file/archive outside server', 'Generate WAL', 'Receive base backups', 'What is pg_receivewal used for?', 'HARD'),
('SQL-standard, better for dump/restore and privileges', 'PostgreSQL', false, 'More types', 'Less storage', 'Faster always', 'SQL-standard, better for dump/restore and privileges', 'Why use generated identity instead of serial?', 'HARD'),
('Auxiliary storage for oversized row values', 'PostgreSQL', false, 'Partitioned table', 'Temp table', 'Auxiliary storage for oversized row values', 'Foreign table', 'What is a toast table?', 'HARD'),
('Backup/restore tool for PostgreSQL', 'PostgreSQL', false, 'Backup/restore tool for PostgreSQL', 'Pooler', 'Vacuum tool', 'FDW', 'What is pg_backrest?', 'HARD'),
('Execute anonymous PL/pgSQL code', 'PostgreSQL', false, 'Execute anonymous PL/pgSQL code', 'Create trigger', 'Define function only', 'Start transaction', 'Why use DO $$ ... $$; blocks?', 'HARD'),
('GiST is balanced tree for many types; GIN is inverted index for composite keys/elements', 'PostgreSQL', false, 'GIN is for geometry only', 'GiST only for text', 'Both identical', 'GiST is balanced tree for many types; GIN is inverted index for composite keys/elements', 'What is the difference between GiST and GIN?', 'HARD'),
('Collect per-operation IO timing for EXPLAIN ANALYZE', 'PostgreSQL', false, 'Track connections', 'Track WAL size', 'Track CPU usage', 'Collect per-operation IO timing for EXPLAIN ANALYZE', 'What does track_io_timing help with?', 'HARD'),
('Throttle autovacuum to reduce IO spikes', 'PostgreSQL', false, 'Accelerate checkpoints', 'Delay pg_dump', 'Tune WAL size', 'Throttle autovacuum to reduce IO spikes', 'What is the effect of vacuum_cost_delay?', 'HARD'),
('Avoid scanning partitions where constraints exclude them', 'PostgreSQL', false, 'Force parallelism', 'Disable indexes', 'Enable RLS', 'Avoid scanning partitions where constraints exclude them', 'Why use partition pruning with constraint_exclusion?', 'HARD'),
('Set of tables to stream changes for', 'PostgreSQL', false, 'A backup policy', 'FDW server', 'Role granting', 'Set of tables to stream changes for', 'What is a logical replication publication?', 'HARD'),
('How much WAL to retain for replicas', 'PostgreSQL', false, 'Max WAL per checkpoint', 'WAL segment size', 'How much WAL to retain for replicas', 'Total WAL size on disk', 'What is wal_keep_size?', 'HARD'),
('Mark tuples with FrozenXID to avoid wraparound', 'PostgreSQL', false, 'Force full rewrite always', 'Sync replica', 'Drop dead rows only', 'Mark tuples with FrozenXID to avoid wraparound', 'What is VACUUM FREEZE used for? (v2)', 'HARD');

--- SQL 

INSERT INTO questions (answer, category, is_deleted, option1, option2, option3, option4, question, question_level) VALUES
('WHERE', 'SQL', false, 'ORDER BY', 'WHERE', 'HAVING', 'GROUP BY', 'Which clause filters rows in a SELECT query?', 'EASY'),
('DISTINCT', 'SQL', false, 'ONLY', 'DISTINCT', 'ALL', 'UNIQUE', 'Which SQL keyword removes duplicate rows from a result set?', 'EASY'),
('ORDER BY', 'SQL', false, 'GROUP BY', 'ALIGN BY', 'ORDER BY', 'SORT BY', 'Which clause sorts the result set?', 'EASY'),
('COUNT()', 'SQL', false, 'COUNT()', 'MAX()', 'SUM()', 'AVG()', 'Which function returns the number of rows?', 'EASY'),
('Uniqueness and NOT NULL', 'SQL', false, 'Only uniqueness', 'Only NOT NULL', 'Foreign reference', 'Uniqueness and NOT NULL', 'What does PRIMARY KEY guarantee?', 'EASY'),
('IS NULL', 'SQL', false, 'IS NULL', 'EQ NULL', '== NULL', '= NULL', 'Which operator checks for missing values?', 'EASY'),
('INTERSECT', 'SQL', false, 'INTERSECT', 'MINUS', 'UNION', 'UNION ALL', 'Which set operation returns common rows of two queries?', 'EASY'),
('GROUP BY', 'SQL', false, 'GROUP BY', 'LIMIT', 'WHERE', 'ORDER BY', 'Which clause groups rows for aggregations?', 'EASY'),
('CREATE TABLE', 'SQL', false, 'ALTER TABLE', 'DEFINE TABLE', 'CREATE TABLE', 'NEW TABLE', 'Which statement creates a new table?', 'EASY'),
('LIMIT/OFFSET', 'SQL', false, 'LIMIT/OFFSET', 'PAGINATE', 'TOP', 'ROWNUM', 'Which keyword limits the number of returned rows (ANSI approach)?', 'EASY'),
('Performs pattern matching', 'SQL', false, 'Joins tables', 'Sorts rows', 'Removes rows', 'Performs pattern matching', 'What does the LIKE operator do?', 'EASY'),
('%', 'SQL', false, '?', '*', '%', '_', 'Which symbol is a wildcard for any sequence of characters in LIKE?', 'EASY'),
('FOREIGN KEY', 'SQL', false, 'CHECK', 'UNIQUE', 'PRIMARY KEY', 'FOREIGN KEY', 'Which SQL constraint enforces a reference to another table?', 'EASY'),
('HAVING', 'SQL', false, 'QUALIFY', 'OVER', 'HAVING', 'WHERE', 'Which clause filters after aggregation?', 'EASY'),
('TRUNCATE TABLE', 'SQL', false, 'DROP TABLE', 'TRUNCATE TABLE', 'REMOVE TABLE', 'DELETE DATABASE', 'Which SQL statement removes all rows but keeps table structure?', 'EASY'),
('MAX()', 'SQL', false, 'UPPER()', 'MAX()', 'HIGHEST()', 'GREATEST()', 'Which function returns the maximum value?', 'EASY'),
('INNER JOIN', 'SQL', false, 'RIGHT JOIN', 'FULL OUTER JOIN', 'INNER JOIN', 'LEFT JOIN', 'Which join returns only matching rows from both tables?', 'EASY'),
('Range inclusion', 'SQL', false, 'Equality', 'Pattern', 'Range inclusion', 'Inequality', 'What does the BETWEEN operator check?', 'EASY'),
('ALTER TABLE ... ADD COLUMN', 'SQL', false, 'CREATE COLUMN', 'APPEND COLUMN', 'UPDATE TABLE ... ADD', 'ALTER TABLE ... ADD COLUMN', 'Which command adds a column to an existing table?', 'EASY'),
('Unique non-null values only', 'SQL', false, 'Duplicate values allowed', 'Unique non-null values only', 'All values must be null', 'Text only', 'What does the UNIQUE constraint ensure?', 'EASY'),
('A subquery that references outer query columns', 'SQL', false, 'A subquery independent of outer query', 'A query with no FROM', 'A query joining itself', 'A subquery that references outer query columns', 'What is a correlated subquery?', 'MEDIUM'),
('LEFT JOIN', 'SQL', false, 'RIGHT JOIN', 'LEFT JOIN', 'INNER JOIN', 'FULL JOIN', 'Which join returns all rows from left table and matching from right?', 'MEDIUM'),
('B-Tree', 'SQL', false, 'Hash', 'Functional/Expression index', 'Bitmap', 'B-Tree', 'Which index type speeds up text pattern search in many RDBMS?', 'MEDIUM'),
('Reducing redundancy and anomalies', 'SQL', false, 'Enabling NoSQL', 'Encrypting data', 'Speeding every query', 'Reducing redundancy and anomalies', 'What is normalization primarily for?', 'MEDIUM'),
('Virtual table based on query', 'SQL', false, 'No access control', 'Stored copy of data', 'Virtual table based on query', 'Automatic indexing', 'What does a VIEW provide?', 'MEDIUM'),
('They are units of work with ACID properties', 'SQL', false, 'They are units of work with ACID properties', 'They cannot be rolled back', 'They must involve multiple tables', 'They auto-commit by default in all DBs', 'Which statement is true about transactions?', 'MEDIUM'),
('READ COMMITTED', 'SQL', false, 'SERIALIZABLE', 'REPEATABLE READ', 'READ COMMITTED', 'READ UNCOMMITTED', 'Which isolation level may allow non-repeatable reads but not dirty reads?', 'MEDIUM'),
('Checks if a subquery returns any rows', 'SQL', false, 'Counts rows', 'Performs a join', 'Checks if a subquery returns any rows', 'Creates tables', 'What does EXISTS do in a WHERE clause?', 'MEDIUM'),
('COUNT(DISTINCT ...)', 'SQL', false, 'HAVING DISTINCT', 'COUNT ALL', 'GROUP BY ALL', 'COUNT(DISTINCT ...)', 'Which clause removes duplicates while aggregating groups?', 'MEDIUM'),
('Primary key on multiple columns', 'SQL', false, 'Primary key on multiple columns', 'Foreign key plus unique', 'Two primary keys', 'Primary key on text only', 'What is a composite primary key?', 'MEDIUM'),
('Deletes referencing rows automatically', 'SQL', false, 'Ignores foreign keys', 'Prevents delete always', 'Converts to soft delete', 'Deletes referencing rows automatically', 'What does ON DELETE CASCADE do?', 'MEDIUM'),
('UNION removes duplicates; UNION ALL keeps them', 'SQL', false, 'UNION preserves duplicates', 'They are identical', 'UNION removes duplicates; UNION ALL keeps them', 'UNION ALL removes duplicates', 'What is the difference between UNION and UNION ALL?', 'MEDIUM'),
('An aggregate over partitions retaining row-granularity', 'SQL', false, 'An aggregate over partitions retaining row-granularity', 'A function for GUI', 'A DDL feature', 'A trigger', 'What is a window function?', 'MEDIUM'),
('Conditional logic in queries', 'SQL', false, 'DDL changes', 'Transaction control', 'Conditional logic in queries', 'Index creation', 'What does the CASE expression provide?', 'MEDIUM'),
('Use IS NULL/IS NOT NULL, not =', 'SQL', false, 'NULL participates in normal equality', 'Use IS NULL/IS NOT NULL, not =', 'NULL = NULL is TRUE', 'NULL is zero', 'Which is true about NULL comparisons?', 'MEDIUM'),
('Introducing redundancy for performance', 'SQL', false, 'Introducing redundancy for performance', 'Encrypting tables', 'Using JSON only', 'Breaking ACID', 'What is denormalization?', 'MEDIUM'),
('Index that includes all columns required to satisfy a query', 'SQL', false, 'Index covering entire table', 'Index that includes all columns required to satisfy a query', 'Index only on PK', 'Bitmap index', 'What is a covering index?', 'MEDIUM'),
('Defines a temporary result set for reuse', 'SQL', false, 'Defines a temporary result set for reuse', 'Creates permanent view', 'Creates a temp table on disk', 'Starts a transaction', 'What does a CTE (WITH clause) do?', 'MEDIUM'),
('IN (...)', 'SQL', false, 'IN (...)', 'EXISTS', 'HAS', 'ANY ONLY', 'Which operator is best for checking set membership?', 'MEDIUM'),
('Hierarchy-based subtotals and grand totals', 'SQL', false, 'Materialized view', 'Hierarchy-based subtotals and grand totals', 'Random ordering', 'Only base groups', 'What does GROUP BY ROLLUP provide?', 'MEDIUM'),
('Two transactions waiting on each other’s locks', 'SQL', false, 'Network timeout', 'Long query', 'Two transactions waiting on each other’s locks', 'Disk full', 'What is a deadlock?', 'MEDIUM'),
('BOOLEAN/BOOL', 'SQL', false, 'INTEGER', 'BOOLEAN/BOOL', 'VARCHAR', 'CHAR(1)', 'Which column type helps store true/false values?', 'MEDIUM'),
('Generated meaningless identifier', 'SQL', false, 'Composite key', 'Generated meaningless identifier', 'Foreign key only', 'Natural business key', 'What is a surrogate key?', 'MEDIUM'),
('HAVING', 'SQL', false, 'FILTER', 'WHERE', 'QUALIFY', 'HAVING', 'Which clause restricts groups after GROUP BY?', 'MEDIUM'),
('Show query execution strategy', 'SQL', false, 'Execute query faster', 'Show query execution strategy', 'Export data', 'Create indexes', 'What is the purpose of EXPLAIN plans?', 'MEDIUM'),
('Stored procedure invoked automatically on events', 'SQL', false, 'CLI script', 'Stored procedure invoked automatically on events', 'Backup job', 'GUI handler', 'What is a trigger?', 'MEDIUM'),
('CHECK', 'SQL', false, 'DEFAULT', 'UNIQUE', 'PRIMARY KEY', 'CHECK', 'Which constraint enforces a boolean expression per row?', 'MEDIUM'),
('A physically stored query result', 'SQL', false, 'A virtual view only', 'A table alias', 'A physically stored query result', 'A log file', 'What is a materialized view?', 'MEDIUM'),
('Returns first non-NULL expression', 'SQL', false, 'Aborts transaction', 'Returns first non-NULL expression', 'Concatenates strings', 'Compares sets', 'What does COALESCE do?', 'MEDIUM'),
('FULL OUTER JOIN', 'SQL', false, 'INNER JOIN', 'LEFT JOIN', 'RIGHT JOIN', 'FULL OUTER JOIN', 'Which join can yield NULLs on both sides when no match?', 'MEDIUM'),
('Auto-incrementing number generator', 'SQL', false, 'Role', 'A table lock', 'Replication slot', 'Auto-incrementing number generator', 'What is a sequence?', 'MEDIUM'),
('ALIAS AS', 'SQL', false, 'RENAME', 'TITLE', 'LABEL', 'ALIAS AS', 'Which clause renames a column in SELECT output?', 'MEDIUM'),
('Enforcing valid foreign key relationships', 'SQL', false, 'Enforcing valid foreign key relationships', 'Using UUIDs', 'Hashing PKs', 'Encrypting references', 'What is referential integrity?', 'MEDIUM'),
('Pick arbitrary row per key', 'SQL', false, 'Pick arbitrary row per key', 'Group only', 'Unique constraint', 'Sort only', 'What does DISTINCT ON (cols) imply (where supported)?', 'MEDIUM'),
('AVG()', 'SQL', false, 'MEAN()', 'COUNT()', 'MEDIAN()', 'AVG()', 'Which function finds average values?', 'MEDIUM'),
('Produces Cartesian product', 'SQL', false, 'Produces Cartesian product', 'Left-only', 'Same as INNER JOIN', 'Returns only matching', 'Which is true about CROSS JOIN?', 'MEDIUM'),
('A marker to partially roll back a transaction', 'SQL', false, 'A marker to partially roll back a transaction', 'A backup copy', 'An index checkpoint', 'A view snapshot', 'What is a savepoint?', 'MEDIUM'),
('LIMIT/OFFSET (or FETCH ... OFFSET ... ROWS)', 'SQL', false, 'ORDER BY only', 'GROUP BY then ORDER', 'HAVING ...', 'LIMIT/OFFSET (or FETCH ... OFFSET ... ROWS)', 'How to paginate results portably?', 'MEDIUM'),
('A copy used for read scaling', 'SQL', false, 'A temp table', 'An index', 'A writable master', 'A copy used for read scaling', 'What is a read replica?', 'MEDIUM'),
('A subquery that references outer query columns', 'SQL', false, 'A query joining itself', 'A subquery independent of outer query', 'A query with no FROM', 'A subquery that references outer query columns', 'What is a correlated subquery? (v2)', 'MEDIUM'),
('REPEATABLE READ (varies by DB)', 'SQL', false, 'REPEATABLE READ (varies by DB)', 'READ UNCOMMITTED', 'SNAPSHOT ONLY', 'READ COMMITTED', 'Which isolation level prevents phantom reads in most RDBMS?', 'HARD'),
('Join to a subquery that depends on left table row', 'SQL', false, 'Cross database join', 'Recursive join only', 'Join to a subquery that depends on left table row', 'GUI windows', 'What is a lateral join (LATERAL) used for?', 'HARD'),
('Low-cardinality columns', 'SQL', false, 'Low-cardinality columns', 'Never', 'High-cardinality columns', 'Only text columns', 'When is a bitmap index preferable?', 'HARD'),
('An index-only scan using all needed columns from index', 'SQL', false, 'An index-only scan using all needed columns from index', 'A full table scan', 'A clustered scan', 'A bitmap heap scan', 'What is a covering index scan?', 'HARD'),
('FRAME BETWEEN ...', 'SQL', false, 'WINDOW RANGE ONLY', 'FRAME BETWEEN ...', 'LIMIT PARTITION', 'GROUP FRAME', 'Which clause defines window frame boundaries?', 'HARD'),
('UPDATE using values from another table correlated by keys', 'SQL', false, 'UPDATE changing PKs only', 'UPDATE without WHERE', 'UPDATE using values from another table correlated by keys', 'A trigger', 'What is a correlated update?', 'HARD'),
('It can return empty due to NULL semantics', 'SQL', false, 'It can return empty due to NULL semantics', 'It ignores NULLs safely', 'It treats NULL as TRUE', 'It is equivalent to NOT EXISTS', 'Why might NOT IN (subquery) be dangerous with NULLs?', 'HARD'),
('Vertical partitioning', 'SQL', false, 'Deferrable constraints', 'CROSS JOIN', 'UNION ALL', 'Vertical partitioning', 'Which strategy reduces write amplification on wide tables?', 'HARD'),
('Checked at transaction commit, not each statement', 'SQL', false, 'Checked at transaction commit, not each statement', 'Immediate check only', 'Disabled always', 'Checked only on SELECT', 'What does DEFERRABLE INITIALLY DEFERRED mean for constraints?', 'HARD'),
('Skip scanning irrelevant partitions', 'SQL', false, 'Fewer indexes', 'Skip scanning irrelevant partitions', 'Better normalization', 'Avoid locks', 'What is the main benefit of partition pruning?', 'HARD'),
('They keep row-level detail while computing aggregates', 'SQL', false, 'They require HAVING', 'They always collapse to one row', 'They disable ORDER BY', 'They keep row-level detail while computing aggregates', 'How do window functions differ from GROUP BY?', 'HARD'),
('Sufficient work_mem/hash memory and hashable join keys', 'SQL', false, 'Only indexes', 'Foreign keys only', 'Sufficient work_mem/hash memory and hashable join keys', 'Natural keys only', 'What does a hash join require to operate efficiently?', 'HARD'),
('Optimizer ignores it without dropping', 'SQL', false, 'It drops the constraint', 'It writes-only', 'Optimizer ignores it without dropping', 'It speeds up queries', 'What is the effect of disabling an index (where supported)?', 'HARD'),
('EXCEPT', 'SQL', false, 'UNION', 'EXCEPT', 'UNION ALL', 'INTERSECT', 'Which set operator is not standard across all RDBMS?', 'HARD'),
('Promotion from row/page to table-level locks', 'SQL', false, 'Snapshotting', 'Promotion from row/page to table-level locks', 'Downgrading locks', 'Deadlock resolution', 'What is lock escalation?', 'HARD'),
('Influence optimizer choices', 'SQL', false, 'Bypass transaction control', 'Encrypt data', 'Return sample rows', 'Influence optimizer choices', 'What’s the purpose of query hints (where available)?', 'HARD'),
('Range queries on the clustering key', 'SQL', false, 'Pure random access', 'Only text search', 'Full scans only', 'Range queries on the clustering key', 'Which scenario benefits most from a clustered index?', 'HARD'),
('Maintain data via insert/update logic atomically', 'SQL', false, 'Drop tables faster', 'Alter schemas live', 'Force full scans', 'Maintain data via insert/update logic atomically', 'Why use MERGE (UPSERT) statements?', 'HARD'),
('Hierarchical queries like org charts', 'SQL', false, 'Hierarchical queries like org charts', 'Sharding', 'Encrypting data', 'MVCC', 'What is a recursive CTE useful for?', 'HARD'),
('SEMI returns rows with a match; ANTI returns rows without a match', 'SQL', false, 'Both return matched', 'SEMI returns rows with a match; ANTI returns rows without a match', 'They are identical', 'Both return unmatched', 'What is the difference between SEMI JOIN and ANTI JOIN (conceptually)?', 'HARD'),
('EXISTS stops at first match and handles NULLs better', 'SQL', false, 'EXISTS requires DISTINCT', 'EXISTS stops at first match and handles NULLs better', 'IN cannot be correlated', 'IN is always faster', 'Why might you prefer EXISTS over IN (subquery)?', 'HARD'),
('Anomaly under snapshot isolation where concurrent writes violate constraints', 'SQL', false, 'Anomaly under snapshot isolation where concurrent writes violate constraints', 'Lost update', 'Deadlock', 'Phantom read', 'What is write skew anomaly?', 'HARD'),
('Using fact/dimension tables with selective join filters', 'SQL', false, 'Using fact/dimension tables with selective join filters', 'Using CROSS JOIN only', 'Only using snowflake schema', 'Avoiding joins', 'What is a star schema optimization in SQL queries?', 'HARD'),
('Join order and plan selection', 'SQL', false, 'Only locking', 'Only storage', 'Join order and plan selection', 'Only caching', 'What does cardinality estimation affect?', 'HARD'),
('Table without clustered/primary ordering', 'SQL', false, 'Read-only', 'In-memory only', 'Table without clustered/primary ordering', 'Only temporary', 'What is a heap table (where applicable)?', 'HARD'),
('Index subset of rows to reduce size and improve speed', 'SQL', false, 'Index all rows always', 'Avoid statistics', 'Index subset of rows to reduce size and improve speed', 'Disable constraints', 'Why use filtered/partial indexes (where supported)?', 'HARD'),
('Refresh optimizer statistics', 'SQL', false, 'Vacuum storage', 'Refresh optimizer statistics', 'Backup data', 'Encrypt data', 'What is the purpose of ANALYZE/UPDATE STATISTICS?', 'HARD'),
('Not an SQL concept', 'SQL', false, 'Window function', 'Index type', 'Join algorithm', 'Not an SQL concept', 'What is a Gantt chart? (trick)', 'HARD'),
('Store computed values for indexing/querying', 'SQL', false, 'Force normalization', 'Replace constraints', 'Store computed values for indexing/querying', 'Always faster than views', 'Why use generated columns (where available)?', 'HARD'),
('Row-level locking', 'SQL', false, 'Table-level', 'Row-level locking', 'DB-level', 'Page-level locking', 'What is tuple locking?', 'HARD'),
('Outcome equivalent to some serial order of transactions', 'SQL', false, 'No deadlocks', 'Outcome equivalent to some serial order of transactions', 'Always fastest', 'No blocking ever', 'What does SERIALIZABLE isolation guarantee conceptually?', 'HARD'),
('Allows referencing left row values in subquery FROM', 'SQL', false, 'Makes it scalar', 'Avoids joins', 'Forbids indexes', 'Allows referencing left row values in subquery FROM', 'What is a lateral correlated subquery advantage?', 'HARD'),
('Hold intermediate results within a session', 'SQL', false, 'Faster than all indexes', 'Persist data across restarts', 'Hold intermediate results within a session', 'Share globally', 'Why might you use a TEMPORARY table?', 'HARD'),
('Search-ARGument-able; can use indexes effectively', 'SQL', false, 'Search-ARGument-able; can use indexes effectively', 'Scalar aggregate', 'Server aggregate', 'Serializable argument', 'What is a sargable predicate?', 'HARD'),
('Many duplicate values', 'SQL', false, 'Many duplicate values', 'Composite keys', 'Smaller tables', 'Unique values', 'Which is a typical cause of poor index selectivity?', 'HARD'),
('Prevents index use; forces scan', 'SQL', false, 'It sorts results', 'Prevents index use; forces scan', 'It breaks SQL', 'It strips accents', 'Why might you avoid leading wildcard in LIKE ''%term''?', 'HARD'),
('REPEATABLE READ (varies by DB)', 'SQL', false, 'READ UNCOMMITTED', 'SNAPSHOT ONLY', 'REPEATABLE READ (varies by DB)', 'READ COMMITTED', 'Which isolation level prevents phantom reads in most RDBMS? (v2)', 'HARD'),
('Join to a subquery that depends on left table row', 'SQL', false, 'GUI windows', 'Cross database join', 'Recursive join only', 'Join to a subquery that depends on left table row', 'What is a lateral join (LATERAL) used for? (v2)', 'HARD'),
('Low-cardinality columns', 'SQL', false, 'Never', 'Low-cardinality columns', 'High-cardinality columns', 'Only text columns', 'When is a bitmap index preferable? (v2)', 'HARD'),
('An index-only scan using all needed columns from index', 'SQL', false, 'A bitmap heap scan', 'A full table scan', 'A clustered scan', 'An index-only scan using all needed columns from index', 'What is a covering index scan? (v2)', 'HARD');

--- Spring Boot

INSERT INTO questions (answer, category, is_deleted, option1, option2, option3, option4, question, question_level) VALUES
-- =========================
-- EASY (20)
-- =========================
('SpringApplication.run()', 'Spring Boot', false, 'configure()', 'run()', 'SpringApplication.run()', 'startApp()', 'Which method is used to start a Spring Boot application?', 'EASY'),
('application.properties', 'Spring Boot', false, 'application.yml', 'bootstrap.properties', 'application.properties', 'config.yaml', 'What is the default properties file in Spring Boot?', 'EASY'),
('Embedded Tomcat', 'Spring Boot', false, 'GlassFish', 'Embedded Tomcat', 'WebSphere', 'WildFly', 'What is the default embedded server for Spring Boot web apps?', 'EASY'),
('@SpringBootApplication', 'Spring Boot', false, '@Configuration', '@SpringBootApplication', '@EnableAutoConfiguration', '@ComponentScan', 'Which annotation combines @Configuration, @EnableAutoConfiguration, and @ComponentScan?', 'EASY'),
('8080', 'Spring Boot', false, '8080', '80', '8443', '9090', 'What is the default HTTP port for a Spring Boot application?', 'EASY'),
('src/main/resources', 'Spring Boot', false, 'src/config', 'src/main/resources', 'resources/public', 'bin', 'Where does Spring Boot look for application.properties by default?', 'EASY'),
('@RestController', 'Spring Boot', false, '@Controller', '@Service', '@RestController', '@Repository', 'Which annotation marks a class as a REST controller?', 'EASY'),
('@GetMapping', 'Spring Boot', false, '@GetMapping', '@FetchMapping', '@QueryMapping', '@MapGet', 'Which annotation maps HTTP GET requests to handler methods?', 'EASY'),
('Actuator', 'Spring Boot', false, 'DevTools', 'Data JPA', 'Actuator', 'Security', 'Which starter exposes health, metrics, and info endpoints?', 'EASY'),
('spring-boot-starter-web', 'Spring Boot', false, 'spring-boot-starter-core', 'spring-boot-starter-web', 'spring-boot-starter-ui', 'spring-boot-starter-tomcat', 'Which starter provides Spring MVC + embedded Tomcat?', 'EASY'),
('@Autowired', 'Spring Boot', false, '@Qualifier', '@Bean', '@Autowired', '@Primary', 'Which annotation injects a dependency by type?', 'EASY'),
('application.yml', 'Spring Boot', false, 'settings.yml', 'application.yml', 'bootstrap.yml', 'config.yml', 'What YAML file can be used instead of application.properties?', 'EASY'),
('spring-boot-starter-test', 'Spring Boot', false, 'spring-test-starter', 'spring-boot-starter-test', 'junit-starter', 'mockito-starter', 'Which starter brings JUnit, Mockito, and Spring Test?', 'EASY'),
('@PathVariable', 'Spring Boot', false, '@PathParam', '@RequestParam', '@PathVariable', '@RequestBody', 'Which annotation binds a URI template variable to a method parameter?', 'EASY'),
('@RequestParam', 'Spring Boot', false, '@RequestParam', '@QueryParam', '@Param', '@FormParam', 'Which annotation binds a query string parameter?', 'EASY'),
('@RequestBody', 'Spring Boot', false, '@Body', '@RequestBody', '@Payload', '@Entity', 'Which annotation binds the HTTP request body to a parameter?', 'EASY'),
('spring-boot-devtools', 'Spring Boot', false, 'spring-boot-hotreload', 'spring-boot-devtools', 'spring-reload-tools', 'devtools-boot', 'Which dependency enables automatic restart and live reload?', 'EASY'),
('banner.txt', 'Spring Boot', false, 'logo.txt', 'banner.txt', 'spring.txt', 'banner.md', 'Which file customizes the startup banner?', 'EASY'),
('Spring Initializr', 'Spring Boot', false, 'Spring Launcher', 'Spring Starter', 'Spring Initializr', 'Spring Wizard', 'What tool generates a new Spring Boot project from the web UI?', 'EASY'),
('pom.xml', 'Spring Boot', false, 'pom.xml', 'build.gradle.kts', 'settings.gradle', 'dependencies.yml', 'In a Maven project, which file declares Spring Boot dependencies?', 'EASY'),

-- =========================
-- MEDIUM (40)
-- =========================
('@EnableAutoConfiguration', 'Spring Boot', false, '@EnableAutoConfiguration', '@AutoConfig', '@EnableConfig', '@AutoSetup', 'Which annotation triggers auto-configuration based on classpath and beans?', 'MEDIUM'),
('CommandLineRunner', 'Spring Boot', false, 'ApplicationRunner', 'CommandLineRunner', 'SpringRunner', 'StartupRunner', 'Which interface lets you run code right after the application starts?', 'MEDIUM'),
('ApplicationRunner provides access to ApplicationArguments', 'Spring Boot', false, 'ApplicationRunner runs before context refresh', 'ApplicationRunner provides access to ApplicationArguments', 'CommandLineRunner is reactive only', 'ApplicationRunner and CommandLineRunner are identical', 'Which statement about ApplicationRunner is true?', 'MEDIUM'),
('profiles', 'Spring Boot', false, 'environments', 'profiles', 'modes', 'flavors', 'In Spring Boot, what feature allows different configurations per environment?', 'MEDIUM'),
('@Profile', 'Spring Boot', false, '@Active', '@Profile', '@Env', '@Stage', 'Which annotation activates a bean for a specific profile?', 'MEDIUM'),
('application-{profile}.properties', 'Spring Boot', false, 'application_{profile}.properties', 'application-{profile}.properties', 'profile.properties', 'env-{profile}.yml', 'What is the naming convention for profile-specific properties?', 'MEDIUM'),
('server.port', 'Spring Boot', false, 'spring.web.port', 'server.port', 'spring.server.http', 'app.port', 'Which property changes the application''s HTTP port?', 'MEDIUM'),
('@ConfigurationProperties', 'Spring Boot', false, '@PropertySource', '@ConfigurationProperties', '@Value', '@PropertyBind', 'Which annotation binds external properties to a POJO?', 'MEDIUM'),
('spring.main.web-application-type=reactive', 'Spring Boot', false, 'spring.web.type=reactive', 'spring.webmvc.mode=reactive', 'spring.main.web-application-type=reactive', 'spring.boot.reactive=true', 'How do you force a reactive WebFlux app via properties?', 'MEDIUM'),
('spring-boot-starter-data-jpa', 'Spring Boot', false, 'spring-data-starter', 'spring-boot-starter-data', 'spring-boot-starter-data-jpa', 'spring-jpa', 'Which starter provides Hibernate/JPA integration?', 'MEDIUM'),
('@Entity', 'Spring Boot', false, '@Table', '@Entity', '@Embeddable', '@Persistence', 'Which annotation marks a JPA entity class?', 'MEDIUM'),
('CrudRepository', 'Spring Boot', false, 'JdbcTemplate', 'CrudRepository', 'JpaTemplate', 'EntityManager', 'Which Spring Data interface exposes basic create/read/update/delete operations?', 'MEDIUM'),
('@Repository', 'Spring Boot', false, '@Component', '@Service', '@Repository', '@Controller', 'Which stereotype marks persistence-layer components?', 'MEDIUM'),
('spring.datasource.url', 'Spring Boot', false, 'spring.jdbc.url', 'spring.datasource.url', 'datasource.url', 'hibernate.url', 'Which property configures the JDBC connection URL?', 'MEDIUM'),
('spring.jpa.hibernate.ddl-auto', 'Spring Boot', false, 'spring.jpa.ddl.auto', 'hibernate.ddl.mode', 'spring.hibernate.ddl', 'spring.jpa.hibernate.ddl-auto', 'Which property controls schema generation (e.g., update, validate)?', 'MEDIUM'),
('@RestControllerAdvice', 'Spring Boot', false, '@ControllerAdvice', '@RestAdvice', '@RestControllerAdvice', '@ExceptionHandler', 'Which annotation combines @ControllerAdvice with @ResponseBody to handle REST errors?', 'MEDIUM'),
('@ExceptionHandler', 'Spring Boot', false, '@Catch', '@ErrorHandler', '@ExceptionHandler', '@Handle', 'Which annotation maps exceptions to handler methods?', 'MEDIUM'),
('spring-boot-starter-validation', 'Spring Boot', false, 'spring-boot-starter-validator', 'spring-boot-starter-validation', 'hibernate-validation-starter', 'spring-validation', 'Which starter brings Bean Validation (Jakarta Validation)?', 'MEDIUM'),
('@Valid', 'Spring Boot', false, '@Verified', '@Valid', '@Validated', '@Constrained', 'Which annotation validates a method parameter or request body?', 'MEDIUM'),
('@Value', 'Spring Boot', false, '@Property', '@Value', '@Config', '@InjectValue', 'Which annotation injects a single property value into a field or constructor param?', 'MEDIUM'),
('@SpringBootTest', 'Spring Boot', false, '@SpringTest', '@BootTest', '@SpringBootTest', '@TestConfiguration', 'Which annotation loads the full application context for integration tests?', 'MEDIUM'),
('TestRestTemplate', 'Spring Boot', false, 'MockMvc', 'WebTestClient', 'TestRestTemplate', 'HttpClient', 'Which helper client is commonly used to call endpoints in @SpringBootTest (servlet stack)?', 'MEDIUM'),
('WebTestClient', 'Spring Boot', false, 'HttpClient', 'RestAssured', 'WebTestClient', 'MockMvc', 'Which client is preferred for testing WebFlux endpoints?', 'MEDIUM'),
('spring-boot-starter-security', 'Spring Boot', false, 'spring-starter-security', 'spring-boot-starter-security', 'spring-boot-security', 'spring-security-starter', 'Which starter adds security filters and config?', 'MEDIUM'),
('BCryptPasswordEncoder', 'Spring Boot', false, 'PlainEncoder', 'NoopPasswordEncoder', 'BCryptPasswordEncoder', 'Sha1Encoder', 'Which PasswordEncoder is commonly used for hashing?', 'MEDIUM'),
('@EnableScheduling', 'Spring Boot', false, '@ScheduledEnable', '@EnableScheduling', '@EnableCron', '@EnableTasks', 'Which annotation enables scheduled tasks?', 'MEDIUM'),
('@Scheduled', 'Spring Boot', false, '@Cron', '@Task', '@Scheduled', '@Job', 'Which annotation marks a method to run on a schedule?', 'MEDIUM'),
('spring.cache.type', 'Spring Boot', false, 'spring.cache.enabled', 'spring.cache.type', 'cache.provider', 'spring.enable.cache', 'Which property selects the cache provider (e.g., caffeine, redis)?', 'MEDIUM'),
('@Cacheable', 'Spring Boot', false, '@Cache', '@CachePut', '@Cacheable', '@CacheEvict', 'Which annotation caches the result of a method call?', 'MEDIUM'),
('springdoc-openapi', 'Spring Boot', false, 'spring-swagger', 'springdoc-openapi', 'spring-boot-swagger', 'swagger-spring', 'Which project auto-generates OpenAPI docs for Spring Boot?', 'MEDIUM'),
('@OpenAPIDefinition', 'Spring Boot', false, '@Api', '@OpenAPIDefinition', '@ApiDoc', '@SwaggerDef', 'Which annotation defines OpenAPI metadata at application level?', 'MEDIUM'),
('spring-boot-starter-mail', 'Spring Boot', false, 'spring-mail', 'spring-boot-starter-mail', 'spring-boot-mail', 'spring-email', 'Which starter is used for sending emails?', 'MEDIUM'),
('@Primary', 'Spring Boot', false, '@Preferred', '@Primary', '@Default', '@Main', 'Which annotation marks a bean as the default when multiple candidates exist?', 'MEDIUM'),
('@Qualifier', 'Spring Boot', false, '@Name', '@Key', '@Qualifier', '@Alias', 'Which annotation helps pick a specific bean among multiple implementations?', 'MEDIUM'),
('@ConditionalOnProperty', 'Spring Boot', false, '@ConditionalOnProperty', '@ConditionOnValue', '@IfProperty', '@PropertyCondition', 'Which conditional loads beans based on a property value?', 'MEDIUM'),
('management.endpoints.web.exposure.include', 'Spring Boot', false, 'actuator.endpoints', 'management.expose', 'management.endpoints.web.exposure.include', 'spring.actuator.include', 'Which property controls which Actuator endpoints are exposed via web?', 'MEDIUM'),
('InfoEndpoint', 'Spring Boot', false, 'StatusEndpoint', 'HealthEndpoint', 'InfoEndpoint', 'MetricsEndpoint', 'Which actuator endpoint shows build/app info when enabled?', 'MEDIUM'),
('HealthIndicator', 'Spring Boot', false, 'HealthProbe', 'HealthIndicator', 'HealthCheck', 'LivenessCheck', 'Which SPI lets you contribute custom health checks?', 'MEDIUM'),
('@DataJpaTest', 'Spring Boot', false, '@JpaTest', '@DataJpaTest', '@RepositoryTest', '@DataTest', 'Which test slice configures in-memory DB and Data JPA components only?', 'MEDIUM'),
('@WebMvcTest', 'Spring Boot', false, '@WebMvcTest', '@MvcSliceTest', '@ControllerTest', '@SpringMvcTest', 'Which test slice configures only MVC controllers and related components?', 'MEDIUM'),
('spring.jackson.serialization.indent_output', 'Spring Boot', false, 'spring.json.pretty', 'spring.jackson.pretty', 'spring.jackson.serialization.indent_output', 'server.json.format', 'Which property enables pretty-printed JSON responses globally?', 'MEDIUM'),
('@Configuration', 'Spring Boot', false, '@Config', '@Configuration', '@BeanConfig', '@SpringConfig', 'Which annotation marks a class that declares one or more @Bean methods?', 'MEDIUM'),
('@Bean', 'Spring Boot', false, '@MakeBean', '@Bean', '@Provide', '@Factory', 'Which annotation declares a bean returned by a method?', 'MEDIUM'),
('@Lazy', 'Spring Boot', false, '@Deferred', '@Lazy', '@Delay', '@Late', 'Which annotation defers bean initialization until first use?', 'MEDIUM'),
('@DependsOn', 'Spring Boot', false, '@After', '@DependsOn', '@Ordered', '@Sequence', 'Which annotation declares initialization order dependencies between beans?', 'MEDIUM'),

-- =========================
-- HARD (40)
-- =========================
('@Conditional', 'Spring Boot', false, '@Autowired', '@Primary', '@Conditional', '@Qualifier', 'Which annotation lets you register a bean based on a custom Condition implementation?', 'HARD'),
('Condition implements matches()', 'Spring Boot', false, 'Condition implements check()', 'Condition implements matchIf()', 'Condition implements matches()', 'Condition implements supports()', 'Which method must a custom org.springframework.context.annotation.Condition implement?', 'HARD'),
('@Import', 'Spring Boot', false, '@Import', '@ScanImport', '@Include', '@BringIn', 'Which annotation imports additional @Configuration classes or registrars?', 'HARD'),
('BeanFactoryPostProcessor', 'Spring Boot', false, 'BeanNameAware', 'BeanFactoryPostProcessor', 'BeanDefinitionReader', 'BeanRegistrar', 'Which interface allows modifying BeanDefinitions before beans are instantiated?', 'HARD'),
('BeanPostProcessor', 'Spring Boot', false, 'BeanPostProcessor', 'SmartInitializer', 'BeanFactoryCustomizer', 'BeanEnhancer', 'Which interface intercepts bean initialization (before/after init methods)?', 'HARD'),
('@EnableConfigurationProperties', 'Spring Boot', false, '@EnableProps', '@EnableConfigurationProperties', '@UseConfigurationProperties', '@EnableExternalProps', 'Which annotation registers @ConfigurationProperties beans without @Component?', 'HARD'),
('ConfigurationPropertiesBinding', 'Spring Boot', false, 'PropertyBinder', 'ConfigurationBinder', 'ConfigurationPropertiesBinding', 'BinderFactory', 'Which mechanism binds complex types to @ConfigurationProperties fields?', 'HARD'),
('spring.factories / AutoConfiguration', 'Spring Boot', false, 'spring.plugins', 'spring.extensions', 'spring.factories / AutoConfiguration', 'spring-autoconfig.xml', 'Which mechanism was used to register auto-configurations prior to the new metadata?', 'HARD'),
('AutoConfiguration class ordering matters', 'Spring Boot', false, 'Order never matters', 'AutoConfiguration class ordering matters', 'Ordering is forbidden', 'Ordering only affects tests', 'Which statement about auto-configuration ordering is correct?', 'HARD'),
('@AutoConfiguration', 'Spring Boot', false, '@AutoConfig', '@AutoConfiguration', '@EnableAutoConfiguration2', '@SmartAuto', 'Which annotation marks a class as a modern (Spring Boot 3) auto-configuration?', 'HARD'),
('ApplicationContextInitializer', 'Spring Boot', false, 'EnvironmentPostProcessor', 'ApplicationContextCustomizer', 'ApplicationContextInitializer', 'ApplicationRunner', 'Which callback can modify the context before it is refreshed?', 'HARD'),
('EnvironmentPostProcessor', 'Spring Boot', false, 'ApplicationRunner', 'ContextLoader', 'EnvironmentPostProcessor', 'Bootstrapper', 'Which SPI lets you add/alter PropertySources before the context starts?', 'HARD'),
('@ServletComponentScan', 'Spring Boot', false, '@WebServletScan', '@ServletComponentScan', '@ScanServlet', '@ServletScan', 'Which annotation scans @WebServlet, @WebFilter, @WebListener for embedded servlet containers?', 'HARD'),
('ReactiveWebServerFactory', 'Spring Boot', false, 'ServletWebServer', 'ServletContextFactory', 'ReactiveWebServerFactory', 'ReactiveContextFactory', 'Which component is responsible for reactive server creation in WebFlux?', 'HARD'),
('ErrorController customization', 'Spring Boot', false, 'ErrorController customization', 'ExceptionHandler only', 'Filter only', 'No override possible', 'What mechanism customizes the /error endpoint globally?', 'HARD'),
('AOT (Ahead-of-Time) processing', 'Spring Boot', false, 'JIT only', 'AOT (Ahead-of-Time) processing', 'Only reflection config', 'No native support', 'Which mode prepares applications for native image runtimes like GraalVM?', 'HARD'),
('@NativeHint', 'Spring Boot', false, '@GraalHint', '@NativeHint', '@ImageHint', '@AOTHint', 'Which Spring Native/GraalVM hint annotation helps include resources and proxies?', 'HARD'),
('Micrometer', 'Spring Boot', false, 'Dropwizard only', 'Micrometer', 'JMX only', 'Slf4j', 'Which metrics facade does Spring Boot Actuator use under the hood?', 'HARD'),
('management.metrics.tags.*', 'Spring Boot', false, 'management.tags.*', 'metrics.tags.*', 'management.metrics.tags.*', 'spring.metrics.tags', 'Which property adds common tags to all exported metrics?', 'HARD'),
('@ControllerAdvice order', 'Spring Boot', false, '@Order on advice class', 'Method name ordering', 'Alphabetical class names', 'Package ordering only', 'How do you control global exception advice precedence?', 'HARD'),
('OncePerRequestFilter', 'Spring Boot', false, 'GenericFilter', 'DelegatingFilterProxy', 'OncePerRequestFilter', 'FilterChainProxy', 'Which filter base class guarantees a single execution per request?', 'HARD'),
('@WebFilter + @ServletComponentScan', 'Spring Boot', false, '@Filter', '@WebFilter only', '@WebFilter + @ServletComponentScan', '@ServletFilter', 'How do you register a custom servlet filter in Boot without FilterRegistrationBean?', 'HARD'),
('ErrorAttributes', 'Spring Boot', false, 'ErrorAttributes', 'ErrorInfoProvider', 'ExceptionAttributes', 'DefaultErrorProps', 'Which component supplies error details to the basic error page/JSON?', 'HARD'),
('spring.mvc.throw-exception-if-no-handler-found=true', 'Spring Boot', false, 'server.throw-404=true', 'spring.web.404=true', 'spring.mvc.throw-exception-if-no-handler-found=true', 'web.throw.notfound', 'Which property turns 404s into exceptions for centralized handling?', 'HARD'),
('@JsonComponent', 'Spring Boot', false, '@JsonConfig', '@JsonComponent', '@JsonBinding', '@JsonCustomizer', 'Which annotation registers custom Jackson serializers/deserializers automatically?', 'HARD'),
('@ConfigurationPropertiesScan', 'Spring Boot', false, '@AutoScanProperties', '@PropertiesScan', '@ConfigurationPropertiesScan', '@EnablePropsScan', 'Which annotation scans for @ConfigurationProperties classes automatically?', 'HARD'),
('SpringApplicationBuilder', 'Spring Boot', false, 'ApplicationBuilder', 'BootBuilder', 'SpringApplicationBuilder', 'ContextBuilder', 'Which builder provides fluent API for hierarchical/parent-child contexts?', 'HARD'),
('ServletWebServerFactory', 'Spring Boot', false, 'ReactiveServerFactory', 'ServletWebServerFactory', 'WebContainerFactory', 'TomcatFactory', 'Which SPI starts the embedded servlet container (Tomcat/Jetty/Undertow)?', 'HARD'),
('FilterRegistrationBean', 'Spring Boot', false, 'FilterConfigBean', 'FilterRegistrationBean', 'FilterBean', 'FilterBinder', 'Which bean type can you register filters programmatically with order?', 'HARD'),
('@Order', 'Spring Boot', false, '@Sequence', '@Priority', '@Order', '@Index', 'Which annotation controls filter/interceptor/advice ordering?', 'HARD'),
('@ConstructorBinding', 'Spring Boot', false, '@BindConstructor', '@ConstructorBinding', '@ConstructorProps', '@BindProps', 'Which annotation binds configuration properties via constructor injection?', 'HARD'),
('Relaxed binding', 'Spring Boot', false, 'Strict binding', 'Relaxed binding', 'Loose binding', 'Rigid binding', 'What is the property binding behavior allowing kebab/camel/underscore variants?', 'HARD'),
('@RecordApplicationEvents', 'Spring Boot', false, '@CaptureEvents', '@RecordAppEvents', '@RecordApplicationEvents', '@AppEvents', 'Which test annotation captures ApplicationEvents for assertions?', 'HARD'),
('ContextRefreshedEvent', 'Spring Boot', false, 'ContextClosedEvent', 'ContextStartedEvent', 'ContextRefreshedEvent', 'ApplicationReadyEvent', 'Which event indicates the ApplicationContext has been initialized or refreshed?', 'HARD'),
('@SpyBean', 'Spring Boot', false, '@Mock', '@Spy', '@SpyBean', '@MockBean', 'Which test annotation registers a Mockito spy in the context?', 'HARD'),
('@AutoConfigureMockMvc', 'Spring Boot', false, '@MockMvcTest', '@AutoConfigureMockMvc', '@EnableMockMvc', '@ConfigureMockMvc', 'Which annotation auto-configures MockMvc for integration tests?', 'HARD'),
('@DirtiesContext', 'Spring Boot', false, '@ResetContext', '@DirtiesContext', '@ClearContext', '@ReloadContext', 'Which test annotation marks the context as dirty to be closed and rebuilt?', 'HARD'),
('@Sql', 'Spring Boot', false, '@RunSql', '@Sql', '@DbScript', '@TestSql', 'Which test annotation executes SQL scripts before/after tests?', 'HARD'),
('@AutoConfigureDataJpa', 'Spring Boot', false, '@DataJpaAutoConfig', '@AutoConfigureDataJpa', '@JpaAutoConfig', '@ConfigureJpa', 'Which annotation configures JPA components for tests without full @DataJpaTest slice?', 'HARD'),
('@SpringBootConfiguration', 'Spring Boot', false, '@BootConfiguration', '@RootConfiguration', '@SpringBootConfiguration', '@ApplicationConfiguration', 'Which annotation is a specialized form of @Configuration for the application class?', 'HARD'),
('ApplicationContextRunner', 'Spring Boot', false, 'ContextTestRunner', 'ApplicationContextRunner', 'ApplicationRunner', 'BootContextRunner', 'Which utility helps test auto-configurations in isolation?', 'HARD'),
('@EnableAutoConfiguration(exclude=...)', 'Spring Boot', false, '@DisableAutoConfiguration', '@EnableAutoConfiguration(exclude=...)', '@ExcludeAutoConfig', '@SkipAutoConfig', 'How do you disable specific auto-configurations declaratively?', 'HARD'),
('spring.autoconfigure.exclude', 'Spring Boot', false, 'spring.boot.auto.exclude', 'spring.autoconfigure.exclude', 'spring.config.exclude', 'boot.autoconfigure.skip', 'Which property disables specific auto-configurations via properties?', 'HARD'),
('SpringFactoriesLoader', 'Spring Boot', false, 'BootFactories', 'SpringFactoriesLoader', 'AutoConfigLoader', 'FactoriesReader', 'Which internal utility historically discovered entries from META-INF/spring.factories?', 'HARD'),
('Native Image', 'Spring Boot', false, 'JIT Image', 'Dynamic Image', 'Native Image', 'Hot Image', 'What is the executable produced by GraalVM when compiling a Spring Boot app ahead of time?', 'HARD');

