name: API Gateway CI

on:
  push:
    paths:
      - 'api-gateway/**'
  pull_request:
    paths:
      - 'api-gateway/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api-gateway

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build Maven Project
        run: mvn clean install

      - name: Verify JAR
        run: ls -la target/

      - name: Build & Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v7
        with:
          image: lakshmanachowdari/online-assessment-platform-jenkins
          tags: api-gateway
          registry: docker.io
          directory: ./api-gateway
          dockerfile: ./api-gateway/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}